events { worker_connections 2048; }

http {
    # Paramètres de stabilité globale
    keepalive_timeout 3600;
    proxy_read_timeout 3600;
    proxy_send_timeout 3600;
    
    server {
        listen 8080;

        location /vless-ws {
            proxy_pass http://169.58.232.36:10001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            # Optimisation ping
            proxy_buffering off;
            tcp_nodelay on;
        }

        location /trojan-ws {
            proxy_pass http://169.58.232.36:10002;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            # Optimisation ping
            proxy_buffering off;
            tcp_nodelay on;
        }
    }
}
